import { Job } from './types';

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    company: 'InnovateTech',
    location: 'San Francisco, CA',
    description: 'Join our team to build next-generation web applications using React, TypeScript, and GraphQL. You will be responsible for creating beautiful and performant user interfaces.',
    required_skills: ['React', 'TypeScript', 'GraphQL', 'CSS-in-JS', 'Webpack'],
    url: 'https://example.com/job/1',
    employmentType: 'Full-time',
    postedDate: '2 days ago',
    relevanceScore: 0,
    minExperience: 5,
    minSalary: 150000,
    maxSalary: 180000,
  },
  {
    id: '2',
    title: 'Full-Stack Developer (Node.js/React)',
    company: 'DataSolutions',
    location: 'New York, NY',
    description: 'We are looking for a skilled Full-Stack Developer to work on both our client-facing React applications and our Node.js microservices. Experience with cloud platforms like AWS is a plus.',
    required_skills: ['React', 'Node.js', 'Express', 'MongoDB', 'AWS', 'Docker'],
    url: 'https://example.com/job/2',
    employmentType: 'Full-time',
    postedDate: '1 week ago',
    relevanceScore: 0,
    minExperience: 3,
    minSalary: 120000,
    maxSalary: 150000,
  },
  {
    id: '3',
    title: 'UI/UX Designer',
    company: 'CreativeMinds',
    location: 'Remote',
    description: 'We need a talented UI/UX designer to create intuitive and visually appealing interfaces for our mobile and web products. A strong portfolio showcasing your design process is required.',
    required_skills: ['Figma', 'Sketch', 'Adobe XD', 'User Research', 'Prototyping'],
    url: 'https://example.com/job/3',
    employmentType: 'Contract',
    postedDate: '5 days ago',
    relevanceScore: 0,
    minExperience: 3,
    minSalary: 80000,
    maxSalary: 110000,
  },
  {
    id: '4',
    title: 'Junior JavaScript Developer',
    company: 'StartUp Co.',
    location: 'Austin, TX',
    description: 'Eager to grow your career? Join our fast-paced environment and learn from senior engineers. You will work with modern JavaScript (ES6+), React, and Redux.',
    required_skills: ['JavaScript', 'HTML', 'CSS', 'React', 'Git'],
    url: 'https://example.com/job/4',
    employmentType: 'Full-time',
    postedDate: '1 month ago',
    relevanceScore: 0,
    minExperience: 1,
    minSalary: 70000,
    maxSalary: 90000,
  },
  {
    id: '5',
    title: 'Lead Backend Engineer (Python)',
    company: 'SecureData Inc.',
    location: 'Boston, MA',
    description: 'Lead a team of backend engineers in developing our Python-based data processing pipeline. Expertise in Django, PostgreSQL, and Celery is required.',
    required_skills: ['Python', 'Django', 'PostgreSQL', 'Celery', 'Redis', 'Team Leadership'],
    url: 'https://example.com/job/5',
    employmentType: 'Full-time',
    postedDate: 'Just now',
    relevanceScore: 0,
    minExperience: 7,
    minSalary: 170000,
    maxSalary: 200000,
  },
   {
    id: '6',
    title: 'DevOps Engineer',
    company: 'CloudLeap',
    location: 'Remote',
    description: 'Automate and streamline our operations and processes. Build and maintain tools for deployment, monitoring, and operations. Troubleshoot and resolve issues in our dev, test, and production environments.',
    required_skills: ['AWS', 'Kubernetes', 'Docker', 'Terraform', 'CI/CD', 'Python'],
    url: 'https://example.com/job/6',
    employmentType: 'Full-time',
    postedDate: '10 days ago',
    relevanceScore: 0,
    minExperience: 4,
    minSalary: 130000,
    maxSalary: 160000,
  },
  {
    id: '7',
    title: 'React Native Developer',
    company: 'MobileFirst',
    location: 'Chicago, IL',
    description: 'Develop and maintain high-quality mobile applications for both iOS and Android using React Native. You will collaborate with product and design teams to deliver a great mobile user experience.',
    required_skills: ['React Native', 'JavaScript', 'iOS', 'Android', 'Redux'],
    url: 'https://example.com/job/7',
    employmentType: 'Full-time',
    postedDate: '2 weeks ago',
    relevanceScore: 0,
    minExperience: 2,
    minSalary: 100000,
    maxSalary: 130000,
  },
];
